export const CLIENT_EVENT = {
    REDIRECT_UNIVERSAL: 'REDIRECT_UNIVERSAL',
    ID_CONVERSATION: 'ID_CONVERSATION',
    CHECK_AUTHEN: 'CHECK_AUTHEN',
    ON_OFF_MODAL: 'ON_OFF_MODAL',
    SYNC_DATA: 'SYNC_DATA',
};

export const SOCKET_EVENT = {
    REQUEST_INVITE_USER: 'REQUEST_INVITE_USER',
    REQUEST_DELETE_CONVERSATION: 'REQUEST_DELETE_CONVERSATION',
    RESPONSE_INVITE_USERS: 'RESPONSE_INVITE_USERS',
    SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
    REQUEST_JOIN_CONVERSATIONS: 'REQUEST_JOIN_CONVERSATIONS',
    RESPONSE_JOIN_CONVERSATIONS: 'RESPONSE_JOIN_CONVERSATIONS',
    REQUEST_JOIN_CONVERSATION: 'REQUEST_JOIN_CONVERSATION',
    RESPONSE_JOIN_CONVERSATION: 'REQUEST_JOIN_CONVERSATION',
    RESPONSE_UPDATE_CONVERSATION: 'RESPONSE_UPDATE_CONVERSATION',
    RESPONSE_CREATE_CONVERSATION: 'RESPONSE_CREATE_CONVERSATION',
    RESPONSE_START_TYPING: 'RESPONSE_START_TYPING',
    RESPONSE_STOP_TYPING: 'RESPONSE_STOP_TYPING',
    RESPONSE_CREATE_MESSAGE: 'RESPONSE_CREATE_MESSAGE',
    DELETE_MESSAGE: 'RESPONSE_DELETE_MESSAGE',
    RESPONSE_LEAVE_CONVERSATION: 'RESPONSE_LEAVE_CONVERSATION',
    WOOF_WOOF: 'WOOF_WOOF',
    MEOW_MEOW: 'MEOW_MEOW',
};
